[book]
authors = ["Pragmatic AI Labs <info@paiml.com>"]
language = "en"
multilingual = false
src = "src"
title = "Entrenar - Training & Optimization Library"
description = "A comprehensive guide to building neural network training systems with autograd, optimizers, LoRA/QLoRA, and quantization using EXTREME TDD methodology"

[build]
build-dir = "book"
create-missing = true
use-default-preprocessors = true

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/paiml/entrenar"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/paiml/entrenar/edit/main/book/{path}"
site-url = "/entrenar/"

[output.html.playground]
editable = true
copyable = true
copy-js = true
runnable = true
